services: docker

env:
  - distro: centos6
  - distro: centos7
  - distro: ubuntu14
  - distro: ubuntu16

script:

  # Download test script
  - wget -O ${PWD}/tests/test-ansible-role.sh https://gist.githubusercontent.com/samdoran/c3d392ee697881fa33a1d1a65814a07b/raw
  - chmod +x ${PWD}/tests/test-ansible-role.sh

  # Run tests
  - ${PWD}/tests/test-ansible-role.sh -d $distro
